### ISSUE TITLE
KeyError: 'estimation'

### ISSUE THREAD

**Issue by hccz95** [lsmcolab/adleap-mas#1]
When I run `python experiment_respawn.py` as your `README.md`, it says:

```
Namespace(agents=7, dim=20, display=False, env='LevelForagingEnv', estimation='OEATE', num_episodes=100, num_exp=0, po=False, tasks=20)
Creating Level Foraging Env #0: 20 7 20
LevelForagingEnv  Visibility: partial  Display: False
Episode : 0
Main Agent Planning
BB: True  - PR: True
Traceback (most recent call last):
  File "experiment_respawn.py", line 192, in <module>
    stats = list_stats(env, accomplished_tasks)
  File "experiment_respawn.py", line 72, in list_stats
    adhoc_agent.smart_parameters['estimation'].get_estimation(env)
KeyError: 'estimation'
```

**Comment by Micanga** [comment]
Hi @hccz95, how are you doing?

Beforehand, sorry for the delay. At the time you opened the issue, we were working on the new fresh version of AdLeap-MAS (updated it last week)
Therefore, your problem may not exist in the published version, since we updated the whole estimation process for the previous and new environments/algorithms inside the framework.

Nevertheless, we plan to release this new version by the end of this week.
Try to update your AdLeap-MAS repository and let us know how it goes.

Cheers.

**Comment by Micanga** [comment]
Hi @hccz95, how are you doing?

Beforehand, sorry for the delay. At the time you opened the issue, we were working on the new fresh version of AdLeap-MAS (updated it last week)
Therefore, your problem may not exist in the published version, since we updated the whole estimation process for the previous and new environments/algorithms inside the framework.

Nevertheless, we plan to release this new version by the end of this week.
Try to update your AdLeap-MAS repository and let us know how it goes.

Cheers.
